name: voz_urbana
description: "Projeto Voz Urbana - Faculdade"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0

  cupertino_icons: ^1.0.8

  # Recursos do dispositivo e mapa
  geolocator: ^11.1.0
  google_maps_flutter: ^2.6.0

  # Banco de dados e persistência
  sqflite: ^2.3.0
  path: ^1.9.0

  # APIs externas
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
