// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf5AuomLNzgn30rvSWouzUO6jfLy0ixi8',
    appId: '1:173733442985:web:cf3144055c8e321c4580b8',
    messagingSenderId: '173733442985',
    projectId: 'voz-urbana-f417a',
    authDomain: 'voz-urbana-f417a.firebaseapp.com',
    storageBucket: 'voz-urbana-f417a.firebasestorage.app',
    measurementId: 'G-J8H03JZ8CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZ1wuV27Kez_rQOp7LbZOVhgr8bwlfZM',
    appId: '1:173733442985:android:9fc75ecc764f232d4580b8',
    messagingSenderId: '173733442985',
    projectId: 'voz-urbana-f417a',
    storageBucket: 'voz-urbana-f417a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXue-a-X6IEClAfkfwUmAa0wDr2NO6Y_E',
    appId: '1:173733442985:ios:30e11de6712cfda74580b8',
    messagingSenderId: '173733442985',
    projectId: 'voz-urbana-f417a',
    storageBucket: 'voz-urbana-f417a.firebasestorage.app',
    iosBundleId: 'com.example.vozUrbana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXue-a-X6IEClAfkfwUmAa0wDr2NO6Y_E',
    appId: '1:173733442985:ios:30e11de6712cfda74580b8',
    messagingSenderId: '173733442985',
    projectId: 'voz-urbana-f417a',
    storageBucket: 'voz-urbana-f417a.firebasestorage.app',
    iosBundleId: 'com.example.vozUrbana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf5AuomLNzgn30rvSWouzUO6jfLy0ixi8',
    appId: '1:173733442985:web:06030f16b8cc4b314580b8',
    messagingSenderId: '173733442985',
    projectId: 'voz-urbana-f417a',
    authDomain: 'voz-urbana-f417a.firebaseapp.com',
    storageBucket: 'voz-urbana-f417a.firebasestorage.app',
    measurementId: 'G-VSSPEXC115',
  );
}
